name: PR Checks
on: 
  pull_request:
    branches:
      - main

jobs:
  format:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Check code formatting
        run: |
          gofmt -s -l .
          test -z $(gofmt -l .)
  token:
    name: Check Any Lingering Secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan for Discord-like tokens
        run: |
          if grep -rE '[a-z0-9_-]{23,28}\.[a-z0-9_-]{6,7}\.[a-z0-9_-]{27}' .; then
            echo "Potential secret detected! Please remove any tokens from the codebase."
            exit 1
          fi
